### ISSUE TITLE
这个库只是个Demo吧？

### ISSUE THREAD

**Issue by codthing** [boyuai/antd-country-phone-input#22]
我打开文档看了看，感觉它更像是个Demo，甚至验证都没有。不知道还有没有在维护。

**Comment by helsonxiao** [comment]
你好。请详细描述你在使用过程中遇到的问题，如果没有问题我将关闭这个 issue。

> 甚至验证都没有

本项目并不负责帮你做验证，请基于业务场景来实现。

下面是一些正在使用本项目的开源网站，希望可以解答你的困惑：
- https://github.com/blockworks-foundation/mango-ui
  - https://github.com/blockworks-foundation/mango-ui/search?q=antd+country
- https://github.com/canonic-dev/canonic-samples
  - https://github.com/canonic-dev/canonic-samples/search?q=antd+country
