### ISSUE TITLE
Setting disabled property only disables the mobile number field

### ISSUE THREAD

**Issue by sharunkumar** [boyuai/antd-country-phone-input#23]
Code:
```
<CountryPhoneInput placeholder="Mobile" inline disabled/>
```
Output:
![image](https://user-images.githubusercontent.com/715417/142885969-32a47163-1f48-43cd-9d7b-df67360d2b4a.png)
![image](https://user-images.githubusercontent.com/715417/142885981-84fa0950-92ad-4511-ad5c-c1201fb1f59b.png)

EDIT:
Looking at the source code, it looks like setting `selectProps={{disabled:true}}` seems to be working, but feels redundant 🤔
Would be better if both the elements could inherit the common property from the control

**Comment by helsonxiao** [comment]
Would you like to create a pr for this feature? BTW I'm considering writing a contributing documentation.

**Comment by sharunkumar** [comment]
I've submitted some changes in #24

**Comment by helsonxiao** [comment]
This is available is 4.2.0, I'll close this issue after contributing doc is done.

**Comment by sharunkumar** [comment]
So I think I had missed out on passing the disabled prop to the input field, I just realized this now after updating the package.
Changes submitted in #25

**Comment by helsonxiao** [comment]
Oops... Could you run the example project and add a demo for it? Some quick tips for you.

```bash
# your working directory
cd antd-country-phone-input
# build this lib
yarn && yarn start
```
```bash
# open another tab
cd antd-country-phone-input/example
yarn && yarn start
```

Then you'll be able to see the example project with your changes in localhost.

**Comment by helsonxiao** [comment]
I'm not sure this prop can work in `lite` mode.

**Comment by sharunkumar** [comment]
I checked the example project in localhost and tried adding `disabled` prop to each, they seem to be working as intended with the latest changes:

![image](https://user-images.githubusercontent.com/715417/144094737-f3f9a876-658c-47e8-8095-c05e61c54733.png)

**Comment by helsonxiao** [comment]
`4.2.1` has been published.
