### ISSUE TITLE
Package path ./dist/index.css is not exported

### ISSUE THREAD

**Issue by Mihai-github** [boyuai/antd-country-phone-input#26]
Hi,

   When I am trying to add `import 'antd-country-phone-input/dist/index.css';` I get this error **Package path ./dist/index.css is not exported from package**.
   Also without it, the input looks okay, but I cannot make the search for country phone code text to have a color.... always is transparent so it's not white because if it was when changing the background color the text should appear.

![image](https://user-images.githubusercontent.com/56633911/149294462-12414274-9072-4c39-87c8-bc4f3a01d686.png)

**Comment by helsonxiao** [comment]
Which version are you using? Try the latest?

**Comment by Mihai-github** [comment]
Found the issue, when trying to type anything the search input shrinks and it's with because for some kind of reason 0px...
Maybe it's because I cannot import the and css.

But adding a min-width solve the problem

![image](https://user-images.githubusercontent.com/56633911/149295192-7f203b9f-f15c-4a43-afbc-e59c4bb39df4.png)

**Comment by helsonxiao** [comment]
Yes, it's a css issue. Take a look at this [demo project](https://github.com/boyuai/antd-country-phone-input/tree/master/example). If your still cannot import the css file(also check `node_modules` or reinstall this package), you can copy the [css](https://github.com/boyuai/antd-country-phone-input/blob/master/src/phone-input.less) into your project directly.

**Comment by Mihai-github** [comment]
@helsonxiao I also have antd lib installed. Maybe is there a config with css files?

`"antd": "^4.2.2",`

**Comment by helsonxiao** [comment]
> When I am trying to add import 'antd-country-phone-input/dist/index.css'; I get this error Package path ./dist/index.css is not exported from package.

I guess it's only related to your project configs. Here's the css file.

![image](https://user-images.githubusercontent.com/26411634/149296672-ac3ccc52-4f6c-4e8c-a3c5-123db9dd0392.png)

**Comment by Mihai-github** [comment]
@helsonxiao This is weird because I can also find it in my node_modules but the import does not work...
Any idea if may be an issue with NextJs projects? 

![image](https://user-images.githubusercontent.com/56633911/149298014-8b4fab72-703d-4d1c-ba95-9da921829ca7.png)

**Comment by helsonxiao** [comment]
Sorry, I've never tested it with nextjs.

> If your still cannot import the css file(also check `node_modules` or reinstall this package), you can copy the [css](https://github.com/boyuai/antd-country-phone-input/blob/master/src/phone-input.less) into your project directly.

**Comment by Mihai-github** [comment]
@helsonxiao Probably this is the issue I guess, right?

**Comment by helsonxiao** [comment]
I'm not sure yet. This package is not optimized for any server-side rendering framework.

**Comment by Mihai-github** [comment]
@helsonxiao That's a bit weird... in theory, it should work, maybe if you have time can you check if there is a specific problem with NextJs with a dummy project? 
If a dummy project works with this lib maybe the project that I'm working on has some issue with it :))

**Comment by helsonxiao** [comment]
I've published `4.3.0` for nextjs. Check this example: https://github.com/boyuai/antd-country-phone-input/tree/master/example-nextjs
