### ISSUE TITLE
How to change the select text from Chinese to English

### ISSUE THREAD

**Issue by roqkabel** [boyuai/antd-country-phone-input#5]
I just installed this module. and I am wondering how to change the country's name from Chinese to English.

I will be glad if there comes any help. Thanks.

**Comment by wangsijie** [comment]
Currentlly not supported, will look into it later.

**Comment by helsonxiao** [comment]
English is the default locale in `3.1.0` now! More locales and features are coming soon.

Example: https://github.com/boyuai/antd-country-phone-input/blob/master/example/src/App.tsx
Online Demo: https://boyuai.github.io/antd-country-phone-input/

If there are any problems, please let us know.
