### ISSUE TITLE
[question] How to validate Select and Input components separately using Antd Form validation?

### ISSUE THREAD

**Issue by felipesilvati** [boyuai/antd-country-phone-input#56]
I'm currently working on a form that looks like this:

```jsx
<Form.Item rules={myRules} hasFeedback>
  <ConfigProvider locale={en}>
     <CountryPhoneInput />
  </ConfigProvider>
</Form.Item>
```

But when the user selects the country, I already get a validation error on both `<Select />` and `<Input />` elements, like this:

![image](https://user-images.githubusercontent.com/33382449/177869350-aa0a6230-cf6a-43dd-ad9e-c2553590eb06.png)

I wonder if there's a way to get a separate validation status like this:
![image](https://user-images.githubusercontent.com/33382449/177868667-5918a88e-da57-4e10-a6d0-e529057bd54d.png)

Thanks!

**Comment by helsonxiao** [comment]
Thanks for your reporting! I am wondering if select component need to be validated. What about just hide ant design's built-in error icon in this case?🤔

**Comment by felipesilvati** [comment]
Fair enough, that should do it for now! Thanks
