### ISSUE TITLE
Sort by country in drop down!

### ISSUE THREAD

**Issue by theonlysandman** [boyuai/antd-country-phone-input#58]
Is there an option to sort by country in the drop-downs?  We have found some situations where website visitors are getting confused without any sorting. 

![phone-number-issue-small](https://user-images.githubusercontent.com/3902931/178271226-c16ffac4-4dc0-4dc8-a370-452d6ad959ca.jpg)

Thanks!

**Comment by helsonxiao** [comment]
There is no sorting option yet. Maybe add a `countries` or `sorter` prop in `Provider` can solve your problem.

Do you have any ideas? Would you like to create a pr for this?

**Comment by jmwakz99** [comment]
Hi I added the sorter prop in the provider as requested.

**Comment by helsonxiao** [comment]
https://github.com/boyuai/antd-country-phone-input/releases/tag/v4.4.0

**Comment by jmwakz99** [comment]
Hi @helsonxiao was it deployed?

**Comment by helsonxiao** [comment]
> Hi @helsonxiao was it deployed?

Actually you can check it in [here](https://www.npmjs.com/package/antd-country-phone-input?activeTab=versions).

**Comment by jmwakz99** [comment]
I tried using it in my project its not working after updating the version to 4.4.0

**Comment by helsonxiao** [comment]
Can you provide more error info about that? It's working perfectly on the [demo page](https://boyuai.github.io/antd-country-phone-input/demos/custom-sorter).

**Comment by jmwakz99** [comment]
I have added areaSorter on the configProvider on my project and when I try to type in the country phone input It does not sort.

**Comment by helsonxiao** [comment]
Sorry, I can't understand what exactly you mean. Do you want to sort the areas after they are filtered? Since this feature is implemented by you. I thought you've already tested it.

The order of filtered areas is controlled by `filterSort` prop of the select component. You can save `areaSorter` in the config context and use it if user provide their own sorter.

https://github.com/boyuai/antd-country-phone-input/blob/master/src/area-select.tsx#L31
https://github.com/boyuai/antd-country-phone-input/blob/master/src/area-select.lite.tsx#L24
https://github.com/boyuai/antd-country-phone-input/blob/master/src/shared.tsx#L18-L22

**Comment by jmwakz99** [comment]
Yeah I tested it and it was working perfectly when I was developing it. But I don't know if it takes sometimes the changes to reflect once deployed to npm I mean accessing it publicly?

**Comment by helsonxiao** [comment]
Try to reinstall `4.4.0` again? It should take effect once published. You can check the dist files in `node_modules` as well.

**Comment by jmwakz99** [comment]
I did try that also it didn't work.

**Comment by helsonxiao** [comment]
Weird... I created a codesandbox. https://codesandbox.io/s/phone-input-2xh1op?file=/src/App.js

It works when dependencies are same as this repo.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/26411634/180677399-1894dcf4-0277-4396-a36d-fcbab929fa78.png">

But if I bump `antd` from `4.13.1` to `4.21.7`, the order is changed.
<img width="276" alt="image" src="https://user-images.githubusercontent.com/26411634/180677561-02c580b3-d45c-406f-af47-4f39b14f6d19.png">
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/26411634/180677635-665eacc3-3811-4991-a946-c02386944950.png">

I'm afraid that I have no time to debug this problem recently. So I will reopen this issue.

**Comment by jmwakz99** [comment]
I noticed this issue is caused by antd version 4.17.0 and above but less than this it works fine. So my suggestion for the time being, you can just specify on the demo/documentation for someone to use sorting his/her antd needs to be version 4.16.13 and below.

**Comment by jmwakz99** [comment]
@helsonxiao I will also debug on my end.

**Comment by helsonxiao** [comment]
@jmwakz99 Thanks!

**Comment by xzedx** [comment]
do we have a solution for that?

**Comment by firflant** [comment]
Yes, I found where was the issue and created a PR that fixes the sorting. The technical aspects are described inside the PR.

**Comment by firflant** [comment]
PR has two approvals. Can we release the fix in version 4.4.1?

**Comment by helsonxiao** [comment]
> PR has two approvals. Can we release the fix in version 4.4.1?

Sure, it has been released. Thanks for your all contributions.

**Comment by firflant** [comment]
Thanks guys for relatively fast release!
