### ISSUE TITLE
Setting default country

### ISSUE THREAD

**Issue by roqkabel** [boyuai/antd-country-phone-input#6]
Please is there a way to set a default country ? .
I would like to know how it is done. Thank you.

**Comment by wangsijie** [comment]
duplicate #5

**Comment by helsonxiao** [comment]
You can use `defaultValue` in `3.3.0` now, and `value` also does the trick for you.

**Comment by yunshangrourou** [comment]
> You can use `defaultValue` in `3.3.0` now, and `value` also does the trick for you.
Neither works.

**Comment by yunshangrourou** [comment]
> You can use `defaultValue` in `3.3.0` now, and `value` also does the trick for you.

Neither works.
