### ISSUE TITLE
Country search input despair while typing 

### ISSUE THREAD

**Issue by Everkers** [boyuai/antd-country-phone-input#8]
Hello, I'm having an issue with this library, whenever I try to use the search input to look for a country it work but I can't see the input's value just the icon.
### Here is my code:

```javascript
    <CountryPhoneInput
      value={{
        phone: values.detail.phone_object.phone
          ? values.detail.phone_object.phone
          : values.detail.phone,
        short: values.detail.phone_object.short
          ? values.detail.phone_object.short
          : "ma",
        code: values.detail.phone_object.code
          ? values.detail.phone_object.code
          : "212",
      }}
      defaultValue={{
        short: "ma",
      }}
      onChange={(value) => {
        setFieldValue("detail.phone_object", value)
      }}
      locale='fr'
      style={inputStyles}
 ```
### Current behavior:
![image](https://user-images.githubusercontent.com/44750827/113928167-50467880-97e6-11eb-8a4d-da70fa687994.png)

**Comment by helsonxiao** [comment]
You may forget to import css file. Add this line in your App.js will make the input width fixed. 
```
import 'antd-country-phone-input/dist/index.css';
```

This should be mentioned in `README.md`, PR is welcome!

**Comment by helsonxiao** [comment]
Basic usage is added in README.md now. If there are any problems, just reopen this issue.
