### ISSUE TITLE
Missing dist/index.m.css in 4.5.0?

### ISSUE THREAD

**Issue by Cattttttttt** [boyuai/antd-country-phone-input#80]
The file `index.m.css` is missing in the `dist` directory of 4.5.0.[here](https://www.npmjs.com/package/antd-country-phone-input/v/4.5.0?activeTab=explore)

And the `package.json` still have
```json
"exports": {
    "./dist/index.css": {
        "import": "./dist/index.m.css",
        "require": "./dist/index.css"
     }
}
```
which cause vite to throw `Error: [vite]: Rollup failed to resolve import "antd-country-phone-input/dist/index.css" from "/SomeProject/index.tsx".` when some components do `import 'antd-country-phone-input/dist/index.css`.

[demo](https://codesandbox.io/p/sandbox/agitated-leavitt-dcnslb?file=%2Fsrc%2FApp.tsx)

**Comment by helsonxiao** [comment]
oops.. can you try `4.5.1`?

**Comment by NotEvenANeko** [comment]
Problem solved, thanks!
